// ============================================================
// utils/shareRoadmap.js
// Web Share API with clipboard fallback
// ============================================================

/**
 * Share roadmap using Web Share API (mobile) or copy to clipboard (desktop).
 * @param {string} topic       - Roadmap topic
 * @param {object} roadmap     - { beginner, intermediate, advanced }
 * @param {function} onToast   - Callback(message) to show toast notification
 */
export async function shareRoadmap(topic, roadmap, onToast) {
  // Build shareable text summary
  const lines = [`🚀 RoadmapAI — Learning Roadmap: ${topic}\n`];

  const stages = [
    { key: "beginner",     emoji: "🌱", label: "Beginner"     },
    { key: "intermediate", emoji: "⚡", label: "Intermediate" },
    { key: "advanced",     emoji: "🚀", label: "Advanced"     },
  ];

  stages.forEach(({ key, emoji, label }) => {
    const items = roadmap[key] || [];
    if (items.length === 0) return;
    lines.push(`${emoji} ${label.toUpperCase()}`);
    items.forEach((item, i) => {
      lines.push(`  ${i + 1}. ${item.topic}`);
    });
    lines.push("");
  });

  lines.push("Generated by RoadmapAI · roadmapai.app");

  const shareText = lines.join("\n");

  // ── Try Web Share API first (works on mobile + some desktop) ──
  if (navigator.share) {
    try {
      await navigator.share({
        title: `RoadmapAI — ${topic} Roadmap`,
        text: shareText,
        url: window.location.href,
      });
      onToast && onToast("✅ Shared successfully!");
      return;
    } catch (err) {
      // User cancelled share — don't show error
      if (err.name === "AbortError") return;
      // Fall through to clipboard
    }
  }

  // ── Fallback: Copy to clipboard ────────────────────────────
  try {
    await navigator.clipboard.writeText(shareText);
    onToast && onToast("📋 Roadmap copied to clipboard!");
  } catch {
    // Last resort: use execCommand (old browsers)
    try {
      const textarea = document.createElement("textarea");
      textarea.value = shareText;
      textarea.style.cssText = "position:fixed;opacity:0;pointer-events:none";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      onToast && onToast("📋 Copied to clipboard!");
    } catch {
      onToast && onToast("❌ Could not copy. Try manually.");
    }
  }
}
